[keys]
alpaca_key = ""
alpaca_secret_key = ""

[live]
strategy = ""
watchlist = ""

[backtesting]
backtesting_days = ""
initial_cash = ""
strategy_list = ""

[ml-variables]
ml_training_lookback = 750
sma_windows = "5, 20, 50"
rsi_window = 14
macd_fast = 12
macd_slow = 26
macd_signal = 9
time_steps = 50
zscore_window = 100